import { Restaurant, RescueBag, CommunityPost, Badge } from '../types';
import { calculateCustomerPrice } from '../utils/pricing';

export const RESTAURANTS: Restaurant[] = [
  {
    id: 'r1',
    name: 'Spice Garden',
    cuisine: 'North Indian',
    city: 'Bengaluru',
    address: '12 Church Street, Indiranagar, Bengaluru',
    rating: 4.7,
    reviewCount: 842,
    verified: true,
    heroImage: 'https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg?auto=compress&cs=tinysrgb&w=800',
    ownerNote: 'We cook with heart and hate waste. Glad you\'re rescuing tonight.',
    description: 'Family-run kitchen serving authentic North Indian curries since 2009.',
  },
  {
    id: 'r2',
    name: 'The Dosa House',
    cuisine: 'South Indian',
    city: 'Bengaluru',
    address: '7 Gandhi Bazaar, Basavanagudi, Bengaluru',
    rating: 4.5,
    reviewCount: 1203,
    verified: true,
    heroImage: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&cs=tinysrgb&w=800',
    ownerNote: 'Every dosa is made fresh. These bags are our way of saying thank you.',
    description: 'Authentic Udupi-style South Indian breakfasts and tiffins.',
  },
  {
    id: 'r3',
    name: 'Bombay Bakes',
    cuisine: 'Bakery & Café',
    city: 'Mumbai',
    address: '34 Hill Road, Bandra West, Mumbai',
    rating: 4.8,
    reviewCount: 567,
    verified: true,
    heroImage: 'https://images.pexels.com/photos/1126359/pexels-photo-1126359.jpeg?auto=compress&cs=tinysrgb&w=800',
    ownerNote: 'Our pastries deserve a good home. Rescue them before midnight.',
    description: 'Artisan bakery crafting sourdoughs, croissants and seasonal pastries daily.',
  },
  {
    id: 'r4',
    name: 'Hyderabadi Daawat',
    cuisine: 'Biryani & Mughlai',
    city: 'Hyderabad',
    address: '45 Banjara Hills Road 2, Hyderabad',
    rating: 4.6,
    reviewCount: 2104,
    verified: true,
    heroImage: 'https://images.pexels.com/photos/7625056/pexels-photo-7625056.jpeg?auto=compress&cs=tinysrgb&w=800',
    ownerNote: 'Dum biryani takes hours to cook. Help us waste none of it.',
    description: 'Legendary dum biryani and Mughlai cuisine from the city of Nizams.',
  },
  {
    id: 'r5',
    name: 'Chennai Tiffin Co.',
    cuisine: 'Tamil Nadu',
    city: 'Chennai',
    address: '8 Anna Salai, T. Nagar, Chennai',
    rating: 4.4,
    reviewCount: 734,
    verified: true,
    heroImage: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&cs=tinysrgb&w=800',
    ownerNote: 'Sambar, rasam, idli — straight from grandmother\'s recipe.',
    description: 'Classic Chennai tiffin and rice meals served with love.',
  },
  {
    id: 'r6',
    name: 'Pune Street Bites',
    cuisine: 'Street Food & Snacks',
    city: 'Pune',
    address: '22 FC Road, Shivajinagar, Pune',
    rating: 4.3,
    reviewCount: 489,
    verified: true,
    heroImage: 'https://images.pexels.com/photos/2116094/pexels-photo-2116094.jpeg?auto=compress&cs=tinysrgb&w=800',
    ownerNote: 'Good vada pav and misal shouldn\'t go to waste. Grab yours!',
    description: 'Authentic Pune street food — vada pav, misal, dabeli and more.',
  },
  {
    id: 'r7',
    name: 'The Green Bowl',
    cuisine: 'Healthy & Salads',
    city: 'Bengaluru',
    address: '15 Koramangala 5th Block, Bengaluru',
    rating: 4.6,
    reviewCount: 321,
    verified: true,
    heroImage: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800',
    ownerNote: 'Clean eating shouldn\'t cost the planet. Rescue these bowls.',
    description: 'Wholesome grain bowls, smoothies and plant-forward meals.',
  },
  {
    id: 'r8',
    name: 'Old Delhi Rolls',
    cuisine: 'Mughlai & Rolls',
    city: 'Delhi',
    address: '3 Connaught Place, New Delhi',
    rating: 4.5,
    reviewCount: 1876,
    verified: true,
    heroImage: 'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&cs=tinysrgb&w=800',
    ownerNote: 'Kati rolls made fresh every evening. Take the last ones home.',
    description: 'Classic Delhi-style kati rolls and kebabs since 1987.',
  },
];

export const RESCUE_BAGS: RescueBag[] = [
  {
    id: 'b1',
    restaurantId: 'r1',
    restaurant: RESTAURANTS[0],
    name: 'Curry Surprise Box',
    description: 'A heartwarming mix of today\'s freshest curries, dal, and hot rotis — a proper home-style meal.',
    originalPrice: 450,
    merchantPrice: 150,
    rescuePrice: calculateCustomerPrice(150),
    stockLeft: 3,
    pickupStart: '7:30 PM',
    pickupEnd: '9:00 PM',
    imageUrl: 'https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg?auto=compress&cs=tinysrgb&w=800',
    possibleContents: ['2 Rotis', 'Dal Makhani', 'Paneer Butter Masala', 'Jeera Rice', 'Raita'],
    allergenNote: 'May contain dairy, gluten. Ask us if unsure.',
    isActive: true,
  },
  {
    id: 'b2',
    restaurantId: 'r2',
    restaurant: RESTAURANTS[1],
    name: 'Tiffin Magic Bag',
    description: 'Fresh idlis, crispy vadas, and steaming sambar — the breakfast you deserve for dinner too.',
    originalPrice: 280,
    merchantPrice: 99,
    rescuePrice: calculateCustomerPrice(99),
    stockLeft: 2,
    pickupStart: '8:00 PM',
    pickupEnd: '9:30 PM',
    imageUrl: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&cs=tinysrgb&w=800',
    possibleContents: ['4 Idlis', '2 Vadas', 'Sambar', 'Coconut Chutney', 'Tomato Chutney'],
    allergenNote: 'Vegetarian. Contains gluten.',
    isActive: true,
  },
  {
    id: 'b3',
    restaurantId: 'r3',
    restaurant: RESTAURANTS[2],
    name: 'Bakery Treasure Bag',
    description: 'A delightful mix of today\'s artisan breads, pastries and buttery treats — impossible to resist.',
    originalPrice: 520,
    merchantPrice: 179,
    rescuePrice: calculateCustomerPrice(179),
    stockLeft: 1,
    pickupStart: '7:00 PM',
    pickupEnd: '8:30 PM',
    imageUrl: 'https://images.pexels.com/photos/1126359/pexels-photo-1126359.jpeg?auto=compress&cs=tinysrgb&w=800',
    possibleContents: ['Sourdough Loaf', '2 Croissants', 'Seasonal Pastry', 'Cookies', 'Mini Tart'],
    allergenNote: 'Contains gluten, dairy, eggs. May contain nuts.',
    isActive: true,
  },
  {
    id: 'b4',
    restaurantId: 'r4',
    restaurant: RESTAURANTS[3],
    name: 'Biryani Bounty Bag',
    description: 'Fragrant dum biryani cooked low and slow — this is the bag that legends are made of.',
    originalPrice: 600,
    merchantPrice: 199,
    rescuePrice: calculateCustomerPrice(199),
    stockLeft: 4,
    pickupStart: '9:00 PM',
    pickupEnd: '10:30 PM',
    imageUrl: 'https://images.pexels.com/photos/7625056/pexels-photo-7625056.jpeg?auto=compress&cs=tinysrgb&w=800',
    possibleContents: ['Chicken/Veg Biryani', 'Mirchi Ka Salan', 'Raita', 'Shorba Soup'],
    allergenNote: 'Non-veg option available. Contains dairy, nuts.',
    isActive: true,
  },
  {
    id: 'b5',
    restaurantId: 'r5',
    restaurant: RESTAURANTS[4],
    name: 'Chennai Comfort Box',
    description: 'Rice, rasam, sambar, and three sabzis — a full South Indian thali in a rescue bag.',
    originalPrice: 320,
    merchantPrice: 119,
    rescuePrice: calculateCustomerPrice(119),
    stockLeft: 2,
    pickupStart: '8:30 PM',
    pickupEnd: '10:00 PM',
    imageUrl: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&cs=tinysrgb&w=800',
    possibleContents: ['Steamed Rice', 'Rasam', 'Sambar', 'Kootu', 'Papad', 'Pickle'],
    allergenNote: 'Fully vegetarian. Contains gluten.',
    isActive: true,
  },
  {
    id: 'b6',
    restaurantId: 'r6',
    restaurant: RESTAURANTS[5],
    name: 'Street Snack Surprise',
    description: 'A fun assortment of Pune\'s best street bites — vada pav, bhel, and spicy misal.',
    originalPrice: 240,
    merchantPrice: 89,
    rescuePrice: calculateCustomerPrice(89),
    stockLeft: 5,
    pickupStart: '6:30 PM',
    pickupEnd: '8:00 PM',
    imageUrl: 'https://images.pexels.com/photos/2116094/pexels-photo-2116094.jpeg?auto=compress&cs=tinysrgb&w=800',
    possibleContents: ['2 Vada Pav', 'Misal Pav', 'Bhel Puri', 'Dabeli', 'Masala Chai'],
    allergenNote: 'Vegetarian. Contains gluten, peanuts.',
    isActive: true,
  },
  {
    id: 'b7',
    restaurantId: 'r7',
    restaurant: RESTAURANTS[6],
    name: 'Wellness Wonder Bag',
    description: 'Nourishing grain bowls, fresh salads and a wholesome smoothie — eat well, feel great.',
    originalPrice: 480,
    merchantPrice: 169,
    rescuePrice: calculateCustomerPrice(169),
    stockLeft: 3,
    pickupStart: '7:00 PM',
    pickupEnd: '8:30 PM',
    imageUrl: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800',
    possibleContents: ['Quinoa Bowl', 'Green Salad', 'Smoothie', 'Protein Bar', 'Fruit Cup'],
    allergenNote: 'Vegan options available. May contain nuts, soy.',
    isActive: true,
  },
  {
    id: 'b8',
    restaurantId: 'r8',
    restaurant: RESTAURANTS[7],
    name: 'Roll Royale Box',
    description: 'Delhi\'s most loved kati rolls, packed hot and ready for the hungry rescuer.',
    originalPrice: 380,
    merchantPrice: 129,
    rescuePrice: calculateCustomerPrice(129),
    stockLeft: 2,
    pickupStart: '8:00 PM',
    pickupEnd: '9:30 PM',
    imageUrl: 'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&cs=tinysrgb&w=800',
    possibleContents: ['2 Chicken Kati Rolls', '1 Paneer Roll', 'Green Chutney', 'Onion Salad'],
    allergenNote: 'Non-veg available. Contains gluten, egg.',
    isActive: true,
  },
];

export const COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: 'cp1',
    userName: 'Priya S.',
    userAvatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=100',
    imageUrl: 'https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg?auto=compress&cs=tinysrgb&w=600',
    caption: 'Rescued the most amazing curry box from Spice Garden! The dal makhani was absolutely divine. Best ₹150 ever spent!',
    restaurantName: 'Spice Garden',
    likes: 47,
    timeAgo: '2h ago',
  },
  {
    id: 'cp2',
    userName: 'Rahul M.',
    userAvatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=100',
    imageUrl: 'https://images.pexels.com/photos/1126359/pexels-photo-1126359.jpeg?auto=compress&cs=tinysrgb&w=600',
    caption: 'Bombay Bakes never disappoints! Got 6 pastries and a sourdough loaf for ₹179. This is truly too good to be true.',
    restaurantName: 'Bombay Bakes',
    likes: 83,
    timeAgo: '5h ago',
  },
  {
    id: 'cp3',
    userName: 'Ananya K.',
    userAvatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=100',
    imageUrl: 'https://images.pexels.com/photos/7625056/pexels-photo-7625056.jpeg?auto=compress&cs=tinysrgb&w=600',
    caption: 'Hyderabadi Daawat biryani rescued! The aroma alone was worth it. Feeling like a true food hero tonight.',
    restaurantName: 'Hyderabadi Daawat',
    likes: 126,
    timeAgo: '1d ago',
  },
];

export const BADGES: Badge[] = [
  { id: 'bd1', name: 'First Rescue', description: 'Made your first rescue', icon: '🌱', earned: true },
  { id: 'bd2', name: 'Weekend Warrior', description: 'Rescued on 3 weekends', icon: '⚡', earned: true },
  { id: 'bd3', name: 'Eco Saver', description: 'Saved 5kg of CO₂', icon: '🍃', earned: true },
  { id: 'bd4', name: 'Local Hero', description: 'Rescued from 10 restaurants', icon: '🏆', earned: false, progress: 7, total: 10 },
  { id: 'bd5', name: 'Streak Master', description: 'Rescued 7 days in a row', icon: '🔥', earned: false, progress: 4, total: 7 },
  { id: 'bd6', name: 'Community Star', description: 'Posted 5 rescue stories', icon: '⭐', earned: false, progress: 2, total: 5 },
];

export const FILTER_CHIPS = [
  { id: 'all', label: 'All Rescues' },
  { id: 'veg', label: 'Veg-Only' },
  { id: 'soon', label: 'Pickup Soon' },
  { id: 'budget', label: 'Under ₹150' },
  { id: 'bakery', label: 'Bakeries' },
  { id: 'biryani', label: 'Biryani' },
  { id: 'nearby', label: 'Nearby' },
];
